CREATE WAREHOUSE IF NOT EXISTS TFL_DEV_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS TFL_DEV;
CREATE SCHEMA IF NOT EXISTS TFL_DEV.RAW;
CREATE SCHEMA IF NOT EXISTS TFL_DEV.STAGING;
CREATE FILE FORMAT IF NOT EXISTS TFL_DEV.RAW.PARQUET_FORMAT TYPE = PARQUET;

CREATE STORAGE INTEGRATION IF NOT EXISTS TFL_S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::388096320305:role/snowflake-tfl-s3-role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://tfl-reliability-raw-percy/arrivals/');

CREATE STAGE IF NOT EXISTS TFL_DEV.RAW.ARRIVALS_STAGE
  URL = 's3://tfl-reliability-raw-percy/arrivals/'
  STORAGE_INTEGRATION = TFL_S3_INT
  FILE_FORMAT = TFL_DEV.RAW.PARQUET_FORMAT;

CREATE TABLE IF NOT EXISTS TFL_DEV.RAW.ARRIVALS (
  raw VARIANT,
  snowflake_loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE PIPE IF NOT EXISTS TFL_DEV.RAW.ARRIVALS_PIPE
  AUTO_INGEST = TRUE
  AS
  COPY INTO TFL_DEV.RAW.ARRIVALS (raw)
    FROM (SELECT $1 FROM @TFL_DEV.RAW.ARRIVALS_STAGE)
    PATTERN = '.*[.]parquet';

USE WAREHOUSE TFL_DEV_WH;
USE SCHEMA TFL_DEV.RAW;

SELECT CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();