CREATE WAREHOUSE IF NOT EXISTS TFL_DEV_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS TFL_DEV;
CREATE SCHEMA IF NOT EXISTS TFL_DEV.RAW;

USE WAREHOUSE TFL_DEV_WH;
USE SCHEMA TFL_DEV.RAW;

SELECT CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();